#!/bin/sh
# executed after postinst!
LOG="/var/log/tmp/$SYNOPKG_PKGNAME.log"
DTFMT="+%Y-%m-%d %H:%M:%S"
echo "$(date "$DTFMT"): postupgrade V$SYNOPKG_PKGVER started ...<br/>" >> "$LOG"
if [[ ! -f "${SYNOPKG_PKGVAR}/config" ]]; then # not e.g. preserved from uninstall
  tempStorageFolder="/tmp/net.reidemeister.$SYNOPKG_PKGNAME" 
  if [ -d "$tempStorageFolder" ]; then
    echo "$(date "$DTFMT"): temp data folder $tempStorageFolder found<br/>" >> "$LOG"
    # restore log
    if [ -f "$tempStorageFolder/log" ]; then
      $(cp -v "$tempStorageFolder/log" "${SYNOPKG_PKGVAR}") 2>&1 >> "$LOG"
      echo "$(date "$DTFMT"): temp logfile copied<br/>" >> "$LOG"
    fi
  fi
else
  echo "$(date "$DTFMT"): 'config' file is already available (from the before executed postinst!)<br/>" >> "$LOG"
fi

# clean-up
rm -r $tempStorageFolder 

echo "$(date "$DTFMT"): ... postupgrade done<br/>" >> "$LOG"
exit 0
