#!/bin/sh
LOG="/var/log/tmp/$SYNOPKG_PKGNAME.log"
if [ "${pkgwizard_remove_settings}" == "true" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S'): preuninst V$SYNOPKG_PKGVER: Continue full uninstall (exit 0) ....<br/>" >> "$LOG"
	exit 0
elif [ "${pkgwizard_remove_settings}" == "false" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S'): preuninst V$SYNOPKG_PKGVER: Preserve Settings via an 'exit 1' ....<br/>" >> "$LOG"
	exit 1
fi
echo "$(date '+%Y-%m-%d %H:%M:%S'): preuninst V$SYNOPKG_PKGVER: Unexpected Value of pkgwizard_remove_settings='${pkgwizard_remove_settings}'<br/>" >> "$LOG"
exit 0
