#!/bin/sh
LOG="/var/log/tmp/$SYNOPKG_PKGNAME.log"
# real uninstall: uninstall wizzard was done and $pkgwizard_remove_settings setup
# update: uninstall wizzard was not done! $pkgwizard_remove_settings was not setup!  
if [ "${pkgwizard_remove_settings}" == "true" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S'): preuninst V$SYNOPKG_PKGVER: Continue full uninstall (exit 0) ....<br/>" >> "$LOG"
	exit 0
elif [ "${pkgwizard_remove_settings}" == "false" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S'): preuninst V$SYNOPKG_PKGVER: Preserve Settings via an 'exit 1' ....<br/>" >> "$LOG"
	exit 1
fi
echo "$(date '+%Y-%m-%d %H:%M:%S'): preuninst V$SYNOPKG_PKGVER: Executed without before WIZZARD_UIFILES/uninstall_uifile_<lng>, e.g. during upgrade<br/>" >> "$LOG"
exit 0
