#!/bin/bash
SCRIPTPATHTHIS="$( cd -- "$(/bin/dirname "$0")" >/dev/null 2>&1 ; /bin/pwd -P )" # /volumeX/@appstore/<app>
APPNAME=${SCRIPTPATHTHIS##*/} # APPNAME="autorun"
source "$SCRIPTPATHTHIS/common" udev # e.g. $APPDATA = "/var/packages/$APPNAME/var" is setup there
echo "$(date "$DTFMT"): udev after common, LOG is now '$LOG'"
# LOG="/var/log/tmp/$APPNAME.log"

TMPPATH="/tmp/net.reidemeister.$APPNAME.$1"  # Marker-File for time stamp to filter events
if [[ -z "$DTFMT" ]]; then
  DTFMT="+%Y-%m-%d %H:%M:%S"
fi
/bin/echo "$(date "$DTFMT"): $0: device '$1' - event received from udev" >> "$LOG"
# /bin/echo "$(date "$DTFMT"): Dump of actual environment:" >> /var/packages/$APPNAME/var/log
# env >> /var/packages/$APPNAME/var/log
# /bin/echo "$(date "$DTFMT"): ... environment done" >> /var/packages/$APPNAME/var/log

# filter duplicate events for 2 minutes
if [ "$(/bin/find "$TMPPATH" -mmin -2)" != "" ] ; then
	logInfo 6 "device '$1' - additional event within 2 minutes for $1 is ignored"
	exit
fi
/bin/touch "$TMPPATH" # to filter subsequent events
# run autorun
logInfo 5 "udev done, starting now $SCRIPTPATHTHIS/autorun"
"$SCRIPTPATHTHIS/autorun" "$1" &
exit

